title: Home
views:
  - panel: true
    path: translucent_material_view
    cards:
      - type: picture-elements
        image: local/bg.png
        elements:
          # markdown fix
          - type: custom:hui-element
            card_type: markdown
            style: { opacity: 0 }
            content: preload

          # Main Backgrond
          - type: image
            style:
              {
                top: 49.24%,
                left: 10.6%,
                width: 21.5%,
                border-right: "1.5px solid rgba(58,69,73,0.2)",
              }
            image: local/sidebar.png
            tap_action:
              action: none
            hold_action:
              action: none

          # Sidebar Clock
          # - entity: sensor.time
          #   type: state-label
          #   style:
          #     {
          #       top: 9%,
          #       left: 11.3%,
          #       color: "rgba(255, 255, 255, 0.7)",
          #       font-size: 5.41vw,
          #       font-weight: 200,
          #     }
          - type: custom:hui-markdown-card
            style: |
              :host {
                top: 9%;
                left: 11.3%;
              }
              ha-card {
                font-size: 5.41vw;
                font-weight: 200;
                box-shadow: none;
                background: none;
              }
              ha-card.type-custom-hui-markdown-card {
                color: rgba(255, 255, 255, 0.7);
                pointer-events: none;
              }
            content: >
              {{ states('sensor.time') }}
            tap_action:
              action: none
            hold_action:
              action: none

          # Sidebar Full Date
          # - entity: sensor.date_string
          #   type: state-label
          #   style:
          #     {
          #       top: 15%,
          #       left: 11.3%,
          #       color: "rgba(255, 255, 255, 0.3)",
          #       font-size: 1.3vw,
          #       font-weight: 600,
          #     }
          - type: custom:hui-markdown-card
            style: |
              :host {
                top: 15%;
                left: 11.3%;
              }
              ha-card {
                font-size: 1.3vw;
                font-weight: 600;
                box-shadow: none;
                background: none;
              }
              ha-card.type-custom-hui-markdown-card {
                color: rgba(255, 255, 255, 0.3);
                pointer-events: none;
              }
            content: >
              {{ states('sensor.date_string') }}
            tap_action:
              action: none
            hold_action:
              action: none

          # System Load Average Title
          - type: custom:hui-markdown-card
            style: |
              :host {
                top: 30%;
                left: 7.7%;
              }
              ha-card {
                font-size: 1.3vw;
                box-shadow: none;
                background: none;
              }
              ha-card.type-custom-hui-markdown-card {
                color: rgba(255, 255, 255, 0.7);
                pointer-events: none;
              }
            content: >
              系统负载

          # System Load Average
          - entity: sensor.load_1m
            type: state-label
            style:
              {
                top: 35%,
                left: 6.1%,
                color: "rgba(255, 255, 255, 0.3)",
                font-size: 1.3vw,
              }
          - entity: sensor.load_5m
            type: state-label
            style:
              {
                top: 35%,
                left: 10.7%,
                color: "rgba(255, 255, 255, 0.3)",
                font-size: 1.3vw,
              }
          - entity: sensor.load_15m
            type: state-label
            style:
              {
                top: 35%,
                left: 15.1%,
                color: "rgba(255, 255, 255, 0.3)",
                font-size: 1.3vw,
              }

          # Button Card
          - type: custom:button-card
            entity: input_boolean.test
            name: hi
            show_icon: true
            style: |
              :host {
                top: 20.35%; 
                left: 30.31%;
                width: 10%;
              }
              ha-card {
                box-shadow: none;
              }
            custom_fields:
              icon_hue: &icon_hue >
                [[[
                  const state = entity.state === 'on' ? 'animate' : null;
                  return `<svg viewBox="0 0 50 50"><style>@keyframes animate{0%{transform: scale(0.85);}20%{transform: scale(1.1);}40%{transform: scale(0.95);}60%{transform: scale(1.03);}80%{transform: scale(0.97);}100%{transform: scale(1);}}.animate{animation: animate 0.8s; transform-origin: center;}</style>
                <path fill="#9da0a2" d="M26.4 25.6c.6-.3 1.1-.7 1.1-1.3L25 17.9l-2.5 6.4c0 .7.6 1.1 1.1 1.3v20.8h-5.5v2.7h13.7v-2.7h-5.5V25.6z"/>
                <path class="${state}" fill="var(--button-card-light-color-no-temperature)" d="M24.6.9l-9.4.5c-.6.1-1.9 0-2.5 2.1s-2.4 9.1-4 16.9c-.2.7-.5 2-.5 2.3s-.4 1.6.9 1.6c.8.1 7.4.3 15.9.3 8.6 0 15.1-.3 15.9-.3 1.3-.1.9-1.3.9-1.6s-.3-1.6-.5-2.3c-1.6-7.8-3.4-14.8-4-16.9s-1.9-2-2.5-2.1c-1.6-.2-6.9-.4-9.4-.5"/> </svg>`;
                ]]]
            styles: &icon_hue_styles
              custom_fields:
                icon_hue:
                  [top: 11%, left: 4.5%, width: 3.05vw, position: absolute]

          # test
          - type: custom:button-card
            entity: input_boolean.test
            name: test
            icon: mdi:fire
            show_icon: true
            style: |
              :host {
                top: 20.35%; 
                left: 42.31%;
                width: 10%;
              }
              ha-card {
                box-shadow: none;
              }
            styles:
              card:
                - width: 100px
                - height: 100px
              grid:
                - grid-template-areas: '"i" "n" "s"'
                - grid-template-columns: 1fr
                - grid-template-rows: 1fr min-content min-content
              name:
                - justify-self: start
                - padding-left: 10px
                - font-weight: bold
                - text-transform: lowercase
              state:
                - justify-self: start
                - padding-left: 10px
            state:
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
