# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"

  - platform: template
    sensors:
      week:
        value_template: >
          {% set weeks = ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"] %}
          {{ weeks[now().weekday()] }}

      month:
        value_template: >
          {{ now().strftime('%m') }}

      day:
        value_template: >
          {{ now().strftime('%d') }}

      date_string:
        friendly_name: "Full Date"
        value_template: "{{ now().year }}-{{ states('sensor.month') }}-{{ states('sensor.day') }} / {{ states('sensor.week') }}"

      last_boot_date_string:
        friendly_name: "Last Boot"
        value_template: '{{ states.sensor.last_boot.state.split("T")[0] }}'

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: memory_use
      - type: swap_use
      - type: disk_use
        arg: /
      - type: last_boot
