title: Home
views:
  - panel: true
    path: translucent_material_view
    cards:
      # Main Backgrond Image
      - type: picture-elements
        style: |
          ha-card {
            border-radius:0;
          }
        image: local/bg.png
        elements:
          # markdown fix
          - type: custom:hui-element
            card_type: markdown
            style: { opacity: 0 }
            content: preload

          # Sidebar Backgrong Image
          - type: custom:hui-element
            element_type: image
            image: local/sidebar.png
            style:
              {
                top: 49.24%,
                left: 10.6%,
                width: 21.5%,
                border-right: "1.5px solid rgba(58,69,73,0.2)",
              }
            tap_action:
              action: none
            hold_action:
              action: none

          # Sidebar Card
          - type: custom:hui-element
            style:
              {
                top: 35%,
                left: 10.6%,
                width: 18vw,
                --ha-card-box-shadow: none,
                --card-background-color: "rgba(255,255,255,0.3)",
              }
            card_type: vertical-stack
            cards:
              # Sidebar Clock
              - type: markdown
                content: "{{ states('sensor.time') }}"
                style: |
                  ha-card {
                    font-size: 5.41vw;
                    font-weight: 100;
                    text-align: center;
                    color: red;
                  }
                  ha-card > ha-markdown.no-header {
                    padding-top: 5.41vw;
                    padding-bottom: 5.41vw; 
                  }

                # Sidebar Full Date
              - type: markdown
                content: "{{ states('sensor.date_string') }}"
                style: |
                  ha-card {
                    font-size: 1.3vw;
                    font-weight: 600;
                    text-align: center;
                    color: blue;
                  }
                  ha-card > ha-markdown.no-header {
                    padding-top: 1.3vw;
                    padding-bottom: 1.3vw;
                    margin-top: -5.5vw;
                  }

              # System States
              - type: entities
                entities:
                  - type: "custom:stack-in-card"
                    mode: horizontal
                    cards:
                      - type: markdown
                        content: 平均负载
                        style: |
                          ha-markdown.no-header {
                            # padding-bottom: 0;
                            # padding-left: 0;
                            # padding-right: 0;
                            # padding-top: 0;
                            padding: 0 !important;
                          }
                      - type: glance
                        entities:
                          - entity: sensor.load_1m
                          - entity: sensor.load_5m
                          - entity: sensor.load_15m
                        show_icon: false
                        show_state: true
                        show_name: false
                        height: 1.9vw
                        style: |
                          div.entities.no-header {
                            # padding-bottom: 0;
                            # padding-left: 0;
                            # padding-right: 0;
                            # padding-top: 0;
                            padding: 0 !important;
                            margin-left: -20px;
                          }
                          div.entity {
                            margin-bottom: 0;
                          }

                  # Laod 1m
                  - entity: sensor.load_1m
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: 1分钟负载
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 1
                    severity:
                      - color: red
                        from: 0.9
                        to: 1
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

                  # Laod 5m
                  - entity: sensor.load_5m
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: 5分钟负载
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 1
                    severity:
                      - color: red
                        from: 0.9
                        to: 1
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

                  # Laod 15m
                  - entity: sensor.load_15m
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: 15分钟负载
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 1
                    severity:
                      - color: red
                        from: 0.9
                        to: 1
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

                  # Processor Use
                  - entity: sensor.processor_use_percent
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: SoC 使用率
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 100
                    severity:
                      - color: red
                        from: 80
                        to: 100
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

                  # Memory Use
                  - entity: sensor.memory_use
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: 内存使用量
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 1970
                    unit_of_measurement: MB
                    severity:
                      - color: red
                        from: 1536
                        to: 1790
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

                  # Disk Use
                  - entity: sensor.disk_use
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: 闪存使用量
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 30.8
                    unit_of_measurement: GB
                    severity:
                      - color: red
                        from: 20
                        to: 30.8
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

                  # Swap
                  - entity: sensor.swap_use
                    type: "custom:bar-card"
                    entity_row: true
                    positions:
                      name: outside
                      icon: "off"
                      indicator: "off"
                      minmax: "off"
                      value: inside
                    name: 交换分区
                    width: 45%
                    height: 1.9vw
                    min: 0
                    max: 492
                    unit_of_measurement: MB
                    severity:
                      - color: red
                        from: 300
                        to: 492
                    style: |
                      ha-card {
                        color: aqua;
                      }
                      bar-card-currentbar,
                      bar-card-backgroundbar,
                      bar-card-contentbar,
                      bar-card-targetbar,
                      bar-card-animationbar {
                        border-radius: 3px;
                      }
                      bar-card-name.name-outside {
                        margin-left: 0px;
                      }

          # Button Card
          - type: custom:button-card
            entity: input_boolean.test
            name: hi
            show_icon: true
            style: |
              :host {
                top: 20.35%; 
                left: 30.31%;
              }
              ha-card {
                box-shadow: none;
              }
            custom_fields:
              icon_hue: >
                [[[
                  const state = entity.state === 'on' ? 'animate' : null;
                  return `<svg viewBox="0 0 50 50"><style>@keyframes animate{0%{transform: scale(0.85);}20%{transform: scale(1.1);}40%{transform: scale(0.95);}60%{transform: scale(1.03);}80%{transform: scale(0.97);}100%{transform: scale(1);}}.animate{animation: animate 0.8s; transform-origin: center;}</style>
                <path fill="#9da0a2" d="M26.4 25.6c.6-.3 1.1-.7 1.1-1.3L25 17.9l-2.5 6.4c0 .7.6 1.1 1.1 1.3v20.8h-5.5v2.7h13.7v-2.7h-5.5V25.6z"/>
                <path class="${state}" fill="var(--button-card-light-color-no-temperature)" d="M24.6.9l-9.4.5c-.6.1-1.9 0-2.5 2.1s-2.4 9.1-4 16.9c-.2.7-.5 2-.5 2.3s-.4 1.6.9 1.6c.8.1 7.4.3 15.9.3 8.6 0 15.1-.3 15.9-.3 1.3-.1.9-1.3.9-1.6s-.3-1.6-.5-2.3c-1.6-7.8-3.4-14.8-4-16.9s-1.9-2-2.5-2.1c-1.6-.2-6.9-.4-9.4-.5"/> </svg>`;
                ]]]
            styles:
              card:
                - width: 9.5vw
                - height: 9.5vw
              custom_fields:
                icon_hue:
                  [top: 11%, left: 4.5%, width: 3.05vw, position: absolute]

          # test
          - type: custom:button-card
            entity: input_boolean.test
            name: 吸顶灯
            icon: mdi:fire
            show_icon: true
            style: |
              :host {
                top: 20.35%; 
                left: 41%;
              }
              ha-card {
                box-shadow: none;
              }
            styles:
              card:
                - width: 9.5vw
                - height: 9.5vw
              # grid:
              #   - grid-template-areas: '"i" "n" "s"'
              #   - grid-template-columns: 1fr
              #   - grid-template-rows: 1fr min-content min-content
              icon:
                - margin-top: -25%
                - margin-left: -55%
              name:
                - justify-self: start
                - padding-left: 0.8vw
                - padding-bottom: 2px
                - font-size: 1.5vw
                - font-weight: 600
              state:
                - justify-self: start
                - padding-left: 1px
            state:
              - value: "on"
                styles:
                  card:
                    - filter: opacity(90%)
              - value: "off"
                styles:
                  card:
                    - filter: opacity(50%)
                  icon:
                    - filter: grayscale(100%)
