title: Home197-iPad-View
background: url("/local/bg.png")
views:
  - panel: true
    path: translucent_material_view
    cards:
      - type: custom:layout-card
        layout: horizontal
        min_columns: 1
        max_columns: 3
        column_width: 245px
        min_width: 245px
        card_options:
        cards:
          - type: custom:mod-card
            style: |
              ha-card {
                padding: 10px;
                color: rgba(255,255,255,0.5);
              }
            card:
              type: grid
              title: Room L
              columns: 2
              cards:
                # Main LED Switch
                - type: custom:button-card
                  style: |
                    ha-card {
                      box-shadow: none;
                    }
                  aspect_ratio: 1/1
                  entity: light.36647026e09806c02f19
                  name: 吸顶灯1
                  show_icon: false
                  show_name: true
                  custom_fields:
                    icon_hue: >
                      [[[
                        const state = entity.state === 'on' ? 'animate' : null;
                        return `<svg viewBox="0 0 50 50"><style>@keyframes animate{0%{transform: scale(0.85);}20%{transform: scale(1.1);}40%{transform: scale(0.95);}60%{transform: scale(1.03);}80%{transform: scale(0.97);}100%{transform: scale(1);}}.animate{animation: animate 0.8s; transform-origin: center;}</style>
                      <path fill="#9da0a2" d="M26.4 25.6c.6-.3 1.1-.7 1.1-1.3L25 17.9l-2.5 6.4c0 .7.6 1.1 1.1 1.3v20.8h-5.5v2.7h13.7v-2.7h-5.5V25.6z"/>
                      <path class="${state}" fill="var(--button-card-light-color-no-temperature)" d="M24.6.9l-9.4.5c-.6.1-1.9 0-2.5 2.1s-2.4 9.1-4 16.9c-.2.7-.5 2-.5 2.3s-.4 1.6.9 1.6c.8.1 7.4.3 15.9.3 8.6 0 15.1-.3 15.9-.3 1.3-.1.9-1.3.9-1.6s-.3-1.6-.5-2.3c-1.6-7.8-3.4-14.8-4-16.9s-1.9-2-2.5-2.1c-1.6-.2-6.9-.4-9.4-.5"/> </svg>`;
                      ]]]
                  styles:
                    card:
                      - border-radius: 10%
                    name:
                      - position: absolute
                      - bottom: 1px
                      - padding-left: 7px
                      - padding-bottom: 5px
                      - font-size: 15px
                      - font-weight: 600
                    custom_fields:
                      icon_hue:
                        [top: 11%, left: 4.5%, width: 32px, position: absolute]
                  state:
                    - value: "on"
                      styles:
                        card:
                          - filter: opacity(90%)
                    - value: "off"
                      styles:
                        card:
                          - filter: opacity(50%)
                        icon:
                          - filter: grayscale(100%)

                # RoomL-Wall-Binary-Sensor Battery
                - type: custom:button-card
                  style: |
                    ha-card {
                      box-shadow: none;
                    }
                  aspect_ratio: 1/1
                  entity: sensor.battery_158d0005883f46
                  name: 无线开关
                  show_icon: false
                  show_name: true
                  custom_fields:
                    icon_battery: >
                      [[[
                        const state = entity.state === 'on' ? 'animate' : null;
                        return `<svg viewBox="0 0 50 50"><style>@keyframes animate{0%{transform: scale(0.85);}20%{transform: scale(1.1);}40%{transform: scale(0.95);}60%{transform: scale(1.03);}80%{transform: scale(0.97);}100%{transform: scale(1);}}.animate{animation: animate 0.8s; transform-origin: center;}</style>
                      <path fill="#9da0a2" d="M26.4 25.6c.6-.3 1.1-.7 1.1-1.3L25 17.9l-2.5 6.4c0 .7.6 1.1 1.1 1.3v20.8h-5.5v2.7h13.7v-2.7h-5.5V25.6z"/>
                      <path class="${state}" fill="var(--button-card-light-color-no-temperature)" d="M24.6.9l-9.4.5c-.6.1-1.9 0-2.5 2.1s-2.4 9.1-4 16.9c-.2.7-.5 2-.5 2.3s-.4 1.6.9 1.6c.8.1 7.4.3 15.9.3 8.6 0 15.1-.3 15.9-.3 1.3-.1.9-1.3.9-1.6s-.3-1.6-.5-2.3c-1.6-7.8-3.4-14.8-4-16.9s-1.9-2-2.5-2.1c-1.6-.2-6.9-.4-9.4-.5"/> </svg>`;
                      ]]]

                    circle: >
                      [[[ return `<svg viewBox="0 0 53 53"><circle cx="26.5" cy="26.5" r="25" stroke="#00000070" stroke-width="1.5" fill="#FFFFFF" /><text x="50%" y="54%" fill="#8d8e90" font-size="20" text-anchor="middle" alignment-baseline="middle">${ states['sensor.battery_158d0005883f46'].state }%</text></svg>`;  ]]]
                  styles:
                    card:
                      - border-radius: 10%
                      - filter: opacity(50%)
                    name:
                      - position: absolute
                      - bottom: 1px
                      - padding-left: 7px
                      - padding-bottom: 5px
                      - font-size: 15px
                      - font-weight: 600
                    custom_fields:
                      icon_battery:
                        [top: 11%, left: 4.5%, width: 32px, position: absolute]
                      circle:
                        [top: 9.5%, right: 8.5%, width: 32px, position: absolute]

                # test3
                - type: custom:button-card
                  style: |
                    ha-card {
                      box-shadow: none;
                    }
                  aspect_ratio: 1/1
                  entity: light.36647026e09806c02f19
                  name: 吸顶灯1
                  show_icon: false
                  show_name: true
                  custom_fields:
                    icon_hue: >
                      [[[
                        const state = entity.state === 'on' ? 'animate' : null;
                        return `<svg viewBox="0 0 50 50"><style>@keyframes animate{0%{transform: scale(0.85);}20%{transform: scale(1.1);}40%{transform: scale(0.95);}60%{transform: scale(1.03);}80%{transform: scale(0.97);}100%{transform: scale(1);}}.animate{animation: animate 0.8s; transform-origin: center;}</style>
                      <path fill="#9da0a2" d="M26.4 25.6c.6-.3 1.1-.7 1.1-1.3L25 17.9l-2.5 6.4c0 .7.6 1.1 1.1 1.3v20.8h-5.5v2.7h13.7v-2.7h-5.5V25.6z"/>
                      <path class="${state}" fill="var(--button-card-light-color-no-temperature)" d="M24.6.9l-9.4.5c-.6.1-1.9 0-2.5 2.1s-2.4 9.1-4 16.9c-.2.7-.5 2-.5 2.3s-.4 1.6.9 1.6c.8.1 7.4.3 15.9.3 8.6 0 15.1-.3 15.9-.3 1.3-.1.9-1.3.9-1.6s-.3-1.6-.5-2.3c-1.6-7.8-3.4-14.8-4-16.9s-1.9-2-2.5-2.1c-1.6-.2-6.9-.4-9.4-.5"/> </svg>`;
                      ]]]
                  styles:
                    card:
                      - border-radius: 10%
                    name:
                      - position: absolute
                      - bottom: 1px
                      - padding-left: 7px
                      - padding-bottom: 5px
                      - font-size: 15px
                      - font-weight: 600
                    custom_fields:
                      icon_hue:
                        [top: 11%, left: 4.5%, width: 32px, position: absolute]
